import type { Metadata } from "next";
// import "./globals.css";
import CustomStyles from "./theme";
import Navbar from "@/components/Navbar";
import { CartProvider } from "@/context/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomStyles>
          <CartProvider>
            <Navbar />
            {children}
          </CartProvider>
        </CustomStyles>
      </body>
    </html>
  );
}
