import type { Metadata } from "next";
// import "./globals.css";
import CustomStyles from "./theme";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
        minHeight: '100vh',
        display: "flex",
        flexDirection: "column"
      }}>
        <CustomStyles>
          <Navbar />
          <main style={{flex:1}}>
          {children}
          </main>
          <Footer />
        </CustomStyles>
      </body>
    </html>
  );
}
